function defaultDB() {
            return {
                users: [
                    { id: 1, name: 'Admin User', email: 'admin@crm.com', role: 'admin', password: 'admin123',
                        avatar: 'A' },
                    { id: 2, name: 'HR Manager', email: 'hr@crm.com', role: 'hr', password: 'hr123', avatar: 'H' },
                    { id: 3, name: 'Emily Chen', email: 'emp@crm.com', role: 'employee', password: 'emp123',
                        avatar: 'E' },
                    { id: 4, name: 'Michael Torres', email: 'michael@crm.com', role: 'employee', password: 'emp123',
                        avatar: 'M' },
                    { id: 5, name: 'Sarah Kim', email: 'sarah@crm.com', role: 'employee', password: 'emp123',
                        avatar: 'S' },
                    { id: 6, name: 'Raj Patel', email: 'raj@crm.com', role: 'employee', password: 'emp123',
                        avatar: 'R' },
                    { id: 7, name: 'Lisa Wong', email: 'lisa@crm.com', role: 'employee', password: 'emp123',
                        avatar: 'L' },
                ],
                employees: [{
                    id: 1,
                    name: 'Emily Chen',
                    email: 'emp@crm.com',
                    department: 'Engineering',
                    position: 'Senior Developer',
                    status: 'active',
                    joined: '2023-06-01',
                    phone: '+1 234 567 890',
                    dob: '1990-05-15',
                    gender: 'Female',
                    bloodGroup: 'A+',
                    maritalStatus: 'Single',
                    nationality: 'American',
                    personalEmail: 'emily@gmail.com',
                    officialEmail: 'emp@crm.com',
                    mobile: '+1 234 567 890',
                    alternate: '+1 234 567 891',
                    address: '123 Main St, NYC',
                    city: 'New York',
                    state: 'NY',
                    country: 'USA',
                    pin: '10001',
                    father: 'Robert Chen',
                    mother: 'Mary Chen',
                    spouse: '',
                    emergencyContact: 'John Doe',
                    emergencyRelation: 'Brother',
                    emergencyPhone: '+1 234 567 892',
                    pan: 'ABCDE1234F',
                    aadhaar: '1234 5678 9012',
                    uan: '123456789012',
                    pfNumber: 'PF123456',
                    esic: 'ESIC123',
                    bankName: 'Chase',
                    accountHolder: 'Emily Chen',
                    accountNumber: '1234567890',
                    ifsc: 'CHAS1234',
                    branch: 'NYC Main',
                    accountType: 'Savings',
                    upi: 'emily@upi',
                    salary: 85000,
                    ctc: 110000,
                    basic: 34000,
                    hra: 17000,
                    conveyance: 8000,
                    special: 26000,
                    grossEarnings: 85000,
                    pf: 4000,
                    esic: 1000,
                    professionalTax: 200,
                    tds: 8500,
                    totalDeduction: 13700,
                    netSalary: 71300,
                    designation: 'Senior Developer',
                    jobGrade: 'L5',
                    employmentType: 'Full Time',
                    reportingManager: 'Admin User',
                    probation: 90,
                    probationEnd: '2023-08-30',
                    confirmationDate: '2023-09-01',
                    employeeCode: 'EMP001',
                    employeeNumber: 'E001',
                    role: 'developer'
                }, {
                    id: 2,
                    name: 'Michael Torres',
                    email: 'michael@crm.com',
                    department: 'Sales',
                    position: 'Sales Manager',
                    status: 'active',
                    joined: '2022-11-15',
                    phone: '+1 345 678 901',
                    dob: '1988-08-20',
                    gender: 'Male',
                    bloodGroup: 'O+',
                    maritalStatus: 'Married',
                    nationality: 'American',
                    personalEmail: 'michael@gmail.com',
                    officialEmail: 'michael@crm.com',
                    mobile: '+1 345 678 901',
                    alternate: '+1 345 678 902',
                    address: '456 Oak Ave, LA',
                    city: 'Los Angeles',
                    state: 'CA',
                    country: 'USA',
                    pin: '90001',
                    father: 'Carlos Torres',
                    mother: 'Maria Torres',
                    spouse: 'Laura Torres',
                    emergencyContact: 'Laura Torres',
                    emergencyRelation: 'Spouse',
                    emergencyPhone: '+1 345 678 903',
                    pan: 'FGHIJ5678K',
                    aadhaar: '5678 9012 3456',
                    uan: '987654321098',
                    pfNumber: 'PF789012',
                    esic: 'ESIC456',
                    bankName: 'Wells Fargo',
                    accountHolder: 'Michael Torres',
                    accountNumber: '9876543210',
                    ifsc: 'WELL1234',
                    branch: 'LA Main',
                    accountType: 'Checking',
                    upi: 'michael@upi',
                    salary: 72000,
                    ctc: 95000,
                    basic: 28800,
                    hra: 14400,
                    conveyance: 7200,
                    special: 21600,
                    grossEarnings: 72000,
                    pf: 3500,
                    esic: 900,
                    professionalTax: 200,
                    tds: 7200,
                    totalDeduction: 11800,
                    netSalary: 60200,
                    designation: 'Sales Manager',
                    jobGrade: 'L4',
                    employmentType: 'Full Time',
                    reportingManager: 'Admin User',
                    probation: 60,
                    probationEnd: '2023-01-14',
                    confirmationDate: '2023-01-15',
                    employeeCode: 'EMP002',
                    employeeNumber: 'E002',
                    role: 'sales'
                }, {
                    id: 3,
                    name: 'Sarah Kim',
                    email: 'sarah@crm.com',
                    department: 'Marketing',
                    position: 'Marketing Lead',
                    status: 'active',
                    joined: '2023-09-10',
                    phone: '+1 456 789 012',
                    dob: '1992-11-25',
                    gender: 'Female',
                    bloodGroup: 'B+',
                    maritalStatus: 'Single',
                    nationality: 'American',
                    personalEmail: 'sarah@gmail.com',
                    officialEmail: 'sarah@crm.com',
                    mobile: '+1 456 789 012',
                    alternate: '+1 456 789 013',
                    address: '789 Pine St, SF',
                    city: 'San Francisco',
                    state: 'CA',
                    country: 'USA',
                    pin: '94101',
                    father: 'David Kim',
                    mother: 'Linda Kim',
                    spouse: '',
                    emergencyContact: 'David Kim',
                    emergencyRelation: 'Father',
                    emergencyPhone: '+1 456 789 014',
                    pan: 'LMNOP9012Q',
                    aadhaar: '9012 3456 7890',
                    uan: '543210987654',
                    pfNumber: 'PF345678',
                    esic: 'ESIC789',
                    bankName: 'Bank of America',
                    accountHolder: 'Sarah Kim',
                    accountNumber: '5678901234',
                    ifsc: 'BOFA1234',
                    branch: 'SF Main',
                    accountType: 'Savings',
                    upi: 'sarah@upi',
                    salary: 68000,
                    ctc: 89000,
                    basic: 27200,
                    hra: 13600,
                    conveyance: 6800,
                    special: 20400,
                    grossEarnings: 68000,
                    pf: 3200,
                    esic: 800,
                    professionalTax: 200,
                    tds: 6800,
                    totalDeduction: 11000,
                    netSalary: 57000,
                    designation: 'Marketing Lead',
                    jobGrade: 'L4',
                    employmentType: 'Full Time',
                    reportingManager: 'Admin User',
                    probation: 60,
                    probationEnd: '2023-11-09',
                    confirmationDate: '2023-11-10',
                    employeeCode: 'EMP003',
                    employeeNumber: 'E003',
                    role: 'marketing'
                }, {
                    id: 4,
                    name: 'James Okafor',
                    email: 'james@crm.com',
                    department: 'Engineering',
                    position: 'DevOps Engineer',
                    status: 'pending',
                    joined: '2024-01-20',
                    phone: '+1 567 890 123',
                    dob: '1991-03-10',
                    gender: 'Male',
                    bloodGroup: 'AB+',
                    maritalStatus: 'Single',
                    nationality: 'Nigerian',
                    personalEmail: 'james@gmail.com',
                    officialEmail: 'james@crm.com',
                    mobile: '+1 567 890 123',
                    alternate: '+1 567 890 124',
                    address: '321 Elm St, Chicago',
                    city: 'Chicago',
                    state: 'IL',
                    country: 'USA',
                    pin: '60601',
                    father: 'Chidi Okafor',
                    mother: 'Ngozi Okafor',
                    spouse: '',
                    emergencyContact: 'Chidi Okafor',
                    emergencyRelation: 'Father',
                    emergencyPhone: '+1 567 890 125',
                    pan: 'QRSTU3456V',
                    aadhaar: '3456 7890 1234',
                    uan: '876543210987',
                    pfNumber: 'PF901234',
                    esic: 'ESIC012',
                    bankName: 'Citibank',
                    accountHolder: 'James Okafor',
                    accountNumber: '9012345678',
                    ifsc: 'CITI1234',
                    branch: 'Chicago Main',
                    accountType: 'Savings',
                    upi: 'james@upi',
                    salary: 65000,
                    ctc: 85000,
                    basic: 26000,
                    hra: 13000,
                    conveyance: 6500,
                    special: 19500,
                    grossEarnings: 65000,
                    pf: 3000,
                    esic: 700,
                    professionalTax: 200,
                    tds: 6500,
                    totalDeduction: 10400,
                    netSalary: 54600,
                    designation: 'DevOps Engineer',
                    jobGrade: 'L3',
                    employmentType: 'Full Time',
                    reportingManager: 'Admin User',
                    probation: 90,
                    probationEnd: '2024-04-19',
                    confirmationDate: '',
                    employeeCode: 'EMP004',
                    employeeNumber: 'E004',
                    role: 'developer'
                }, {
                    id: 5,
                    name: 'Priya Sharma',
                    email: 'priya@crm.com',
                    department: 'HR',
                    position: 'HR Coordinator',
                    status: 'active',
                    joined: '2023-04-05',
                    phone: '+1 678 901 234',
                    dob: '1993-07-12',
                    gender: 'Female',
                    bloodGroup: 'A-',
                    maritalStatus: 'Married',
                    nationality: 'Indian',
                    personalEmail: 'priya@gmail.com',
                    officialEmail: 'priya@crm.com',
                    mobile: '+1 678 901 234',
                    alternate: '+1 678 901 235',
                    address: '654 Cedar St, Dallas',
                    city: 'Dallas',
                    state: 'TX',
                    country: 'USA',
                    pin: '75201',
                    father: 'Ravi Sharma',
                    mother: 'Anita Sharma',
                    spouse: 'Vikram Singh',
                    emergencyContact: 'Vikram Singh',
                    emergencyRelation: 'Spouse',
                    emergencyPhone: '+1 678 901 236',
                    pan: 'UVWXY7890Z',
                    aadhaar: '7890 1234 5678',
                    uan: '210987654321',
                    pfNumber: 'PF567890',
                    esic: 'ESIC345',
                    bankName: 'Chase',
                    accountHolder: 'Priya Sharma',
                    accountNumber: '2345678901',
                    ifsc: 'CHAS5678',
                    branch: 'Dallas Main',
                    accountType: 'Savings',
                    upi: 'priya@upi',
                    salary: 58000,
                    ctc: 75000,
                    basic: 23200,
                    hra: 11600,
                    conveyance: 5800,
                    special: 17400,
                    grossEarnings: 58000,
                    pf: 2700,
                    esic: 600,
                    professionalTax: 200,
                    tds: 5800,
                    totalDeduction: 9300,
                    netSalary: 48700,
                    designation: 'HR Coordinator',
                    jobGrade: 'L3',
                    employmentType: 'Full Time',
                    reportingManager: 'Admin User',
                    probation: 60,
                    probationEnd: '2023-06-04',
                    confirmationDate: '2023-06-05',
                    employeeCode: 'EMP005',
                    employeeNumber: 'E005',
                    role: 'hr'
                }, {
                    id: 6,
                    name: 'Raj Patel',
                    email: 'raj@crm.com',
                    department: 'Sales',
                    position: 'Telecaller',
                    status: 'active',
                    joined: '2024-02-01',
                    phone: '+1 789 012 345',
                    dob: '1995-09-05',
                    gender: 'Male',
                    bloodGroup: 'O-',
                    maritalStatus: 'Single',
                    nationality: 'Indian',
                    personalEmail: 'raj@gmail.com',
                    officialEmail: 'raj@crm.com',
                    mobile: '+1 789 012 345',
                    alternate: '+1 789 012 346',
                    address: '987 Spruce St, Atlanta',
                    city: 'Atlanta',
                    state: 'GA',
                    country: 'USA',
                    pin: '30301',
                    father: 'Kumar Patel',
                    mother: 'Sita Patel',
                    spouse: '',
                    emergencyContact: 'Kumar Patel',
                    emergencyRelation: 'Father',
                    emergencyPhone: '+1 789 012 347',
                    pan: 'ABCDE5678F',
                    aadhaar: '5678 1234 9012',
                    uan: '654321098765',
                    pfNumber: 'PF234567',
                    esic: 'ESIC678',
                    bankName: 'Wells Fargo',
                    accountHolder: 'Raj Patel',
                    accountNumber: '3456789012',
                    ifsc: 'WELL5678',
                    branch: 'Atlanta Main',
                    accountType: 'Savings',
                    upi: 'raj@upi',
                    salary: 42000,
                    ctc: 55000,
                    basic: 16800,
                    hra: 8400,
                    conveyance: 4200,
                    special: 12600,
                    grossEarnings: 42000,
                    pf: 2000,
                    esic: 500,
                    professionalTax: 200,
                    tds: 4200,
                    totalDeduction: 6900,
                    netSalary: 35100,
                    designation: 'Telecaller',
                    jobGrade: 'L2',
                    employmentType: 'Full Time',
                    reportingManager: 'Michael Torres',
                    probation: 60,
                    probationEnd: '2024-04-01',
                    confirmationDate: '',
                    employeeCode: 'EMP006',
                    employeeNumber: 'E006',
                    role: 'telecaller'
                }, {
                    id: 7,
                    name: 'Lisa Wong',
                    email: 'lisa@crm.com',
                    department: 'Marketing',
                    position: 'Social Media Manager',
                    status: 'active',
                    joined: '2023-11-15',
                    phone: '+1 890 123 456',
                    dob: '1994-02-28',
                    gender: 'Female',
                    bloodGroup: 'AB-',
                    maritalStatus: 'Single',
                    nationality: 'American',
                    personalEmail: 'lisa@gmail.com',
                    officialEmail: 'lisa@crm.com',
                    mobile: '+1 890 123 456',
                    alternate: '+1 890 123 457',
                    address: '246 Birch St, Seattle',
                    city: 'Seattle',
                    state: 'WA',
                    country: 'USA',
                    pin: '98101',
                    father: 'Michael Wong',
                    mother: 'Jennifer Wong',
                    spouse: '',
                    emergencyContact: 'Michael Wong',
                    emergencyRelation: 'Father',
                    emergencyPhone: '+1 890 123 458',
                    pan: 'FGHIJ9012K',
                    aadhaar: '9012 5678 3456',
                    uan: '432109876543',
                    pfNumber: 'PF456789',
                    esic: 'ESIC901',
                    bankName: 'Bank of America',
                    accountHolder: 'Lisa Wong',
                    accountNumber: '4567890123',
                    ifsc: 'BOFA5678',
                    branch: 'Seattle Main',
                    accountType: 'Savings',
                    upi: 'lisa@upi',
                    salary: 55000,
                    ctc: 72000,
                    basic: 22000,
                    hra: 11000,
                    conveyance: 5500,
                    special: 16500,
                    grossEarnings: 55000,
                    pf: 2600,
                    esic: 600,
                    professionalTax: 200,
                    tds: 5500,
                    totalDeduction: 8900,
                    netSalary: 46100,
                    designation: 'Social Media Manager',
                    jobGrade: 'L3',
                    employmentType: 'Full Time',
                    reportingManager: 'Sarah Kim',
                    probation: 60,
                    probationEnd: '2024-01-14',
                    confirmationDate: '2024-01-15',
                    employeeCode: 'EMP007',
                    employeeNumber: 'E007',
                    role: 'socialmedia'
                }, ],
                shifts: [
                    { id: 1, name: 'Morning Shift', startTime: '09:00', endTime: '18:00', breakDuration: '60',
                        gracePeriod: '15', weeklyOff: 'Sunday', nightShift: false, shiftAllowance: 0,
                        status: 'active' },
                    { id: 2, name: 'Night Shift', startTime: '22:00', endTime: '06:00', breakDuration: '60',
                        gracePeriod: '15', weeklyOff: 'Monday', nightShift: true, shiftAllowance: 5000,
                        status: 'active' },
                ],
                leaveTypes: [
                    { id: 1, name: 'Casual Leave', code: 'CL', maxDays: 12, carryForward: true, encashment: true },
                    { id: 2, name: 'Sick Leave', code: 'SL', maxDays: 10, carryForward: false, encashment: false },
                    { id: 3, name: 'Earned Leave', code: 'EL', maxDays: 15, carryForward: true, encashment: true },
                    { id: 4, name: 'Maternity Leave', code: 'ML', maxDays: 180, carryForward: false,
                        encashment: false },
                    { id: 5, name: 'Paternity Leave', code: 'PL', maxDays: 15, carryForward: false,
                        encashment: false },
                    { id: 6, name: 'Comp Off', code: 'CO', maxDays: 5, carryForward: true, encashment: false },
                ],
                leaves: [
                    { id: 1, employeeId: 1, type: 'Casual Leave', startDate: '2026-08-10', endDate: '2026-08-12',
                        totalDays: 3, reason: 'Family event', status: 'approved', appliedDate: '2026-08-01',
                        approvedBy: 'Admin User' },
                    { id: 2, employeeId: 2, type: 'Sick Leave', startDate: '2026-08-05', endDate: '2026-08-05',
                        totalDays: 1, reason: 'Fever', status: 'pending', appliedDate: '2026-08-05',
                        approvedBy: '' },
                ],
                attendance: [
                    { id: 1, employeeId: 1, date: '2026-08-01', checkIn: '09:05', checkOut: '18:10',
                        totalHours: 9.08, status: 'present', lateMinutes: 5, overtimeHours: 0.17,
                        shift: 'Morning' },
                    { id: 2, employeeId: 2, date: '2026-08-01', checkIn: '08:55', checkOut: '18:00',
                        totalHours: 9.08, status: 'present', lateMinutes: 0, overtimeHours: 0,
                        shift: 'Morning' },
                    { id: 3, employeeId: 3, date: '2026-08-01', checkIn: '00:00', checkOut: '00:00',
                        totalHours: 0, status: 'absent', lateMinutes: 0, overtimeHours: 0, shift: 'Morning' },
                    { id: 4, employeeId: 4, date: '2026-08-01', checkIn: '09:00', checkOut: '18:05',
                        totalHours: 9.08, status: 'present', lateMinutes: 0, overtimeHours: 0.08,
                        shift: 'Morning' },
                    { id: 5, employeeId: 5, date: '2026-08-01', checkIn: '09:00', checkOut: '18:00',
                        totalHours: 9, status: 'present', lateMinutes: 0, overtimeHours: 0, shift: 'Morning' },
                    { id: 6, employeeId: 6, date: '2026-08-01', checkIn: '08:50', checkOut: '18:15',
                        totalHours: 9.42, status: 'present', lateMinutes: 0, overtimeHours: 0.25,
                        shift: 'Morning' },
                    { id: 7, employeeId: 7, date: '2026-08-01', checkIn: '09:10', checkOut: '18:20',
                        totalHours: 9.17, status: 'present', lateMinutes: 10, overtimeHours: 0.33,
                        shift: 'Morning' },
                ],
                requisitions: [
                    { id: 1, department: 'Engineering', position: 'Senior React Developer', vacancies: 2,
                        hiringManager: 'Admin User', recruiter: 'Priya Sharma', experience: '5+ years',
                        qualification: 'B.Tech', skills: 'React,TypeScript,Node.js', salaryRange: '80000-120000',
                        employmentType: 'Full Time', location: 'NYC', workMode: 'Hybrid', priority: 'High',
                        deadline: '2026-09-30', status: 'open' },
                    { id: 2, department: 'Sales', position: 'Sales Executive', vacancies: 3,
                        hiringManager: 'Michael Torres', recruiter: 'Priya Sharma', experience: '2+ years',
                        qualification: 'Any Graduate', skills: 'Communication,CRM', salaryRange: '40000-60000',
                        employmentType: 'Full Time', location: 'LA', workMode: 'Onsite', priority: 'Medium',
                        deadline: '2026-08-30', status: 'interviewing' },
                ],
                candidates: [
                    { id: 1, name: 'John Miller', mobile: '+1 234 567 999', email: 'john@email.com',
                        location: 'NYC', qualification: 'M.Tech', experience: '6 years', currentCompany: 'TechCorp',
                        currentSalary: 90000, expectedSalary: 110000, noticePeriod: '30 days',
                        skills: 'React,TS,Node', source: 'LinkedIn', recruiter: 'Priya Sharma',
                        status: 'interviewed', score: 85 },
                    { id: 2, name: 'Anna Kowalski', mobile: '+1 345 678 999', email: 'anna@email.com',
                        location: 'LA', qualification: 'MBA', experience: '4 years', currentCompany: 'SalesPro',
                        currentSalary: 55000, expectedSalary: 65000, noticePeriod: '15 days',
                        skills: 'Sales,CRM,LeadGen', source: 'Referral', recruiter: 'Priya Sharma',
                        status: 'shortlisted', score: 78 },
                ],
                interviews: [
                    { id: 1, candidateId: 1, position: 'Senior React Developer', round: 'Technical Round 1',
                        interviewer: 'Admin User', date: '2026-08-10', time: '10:00 AM', mode: 'Video',
                        technicalScore: 8, communicationScore: 7, domainScore: 9, problemSolvingScore: 8,
                        culturalFit: 7, overallScore: 7.8, recommendation: 'Proceed', status: 'completed' },
                ],
                onboarding: [
                    { id: 1, candidateId: 1, joiningDate: '2026-09-01', joiningLocation: 'NYC',
                        reportingManager: 'Admin User', employeeId: 8, documents: 'Pending', kyc: 'Pending',
                        bankDetails: 'Pending', emailCreated: false, erpAccount: false, laptopAssigned: false,
                        idCard: false, accessCard: false, trainingAssigned: false, orientation: false,
                        policyAcceptance: false, ndaSigned: false, bgv: false, completion: 15,
                        status: 'in-progress' },
                ],
                kpiTemplates: [
                    { id: 1, role: 'telecaller', name: 'Calls Per Day', target: 100, weightage: 25 },
                    { id: 2, role: 'telecaller', name: 'Conversion Rate', target: 20, weightage: 30 },
                    { id: 3, role: 'telecaller', name: 'Lead Qualification', target: 30, weightage: 20 },
                    { id: 4, role: 'telecaller', name: 'Call Quality', target: 90, weightage: 15 },
                    { id: 5, role: 'telecaller', name: 'Attendance', target: 95, weightage: 10 },
                    { id: 6, role: 'socialmedia', name: 'Content Posts', target: 20, weightage: 20 },
                    { id: 7, role: 'socialmedia', name: 'Engagement Rate', target: 5, weightage: 30 },
                    { id: 8, role: 'socialmedia', name: 'Follower Growth', target: 10, weightage: 20 },
                    { id: 9, role: 'socialmedia', name: 'Leads Generated', target: 5, weightage: 20 },
                    { id: 10, role: 'socialmedia', name: 'Brand Compliance', target: 95, weightage: 10 },
                    { id: 11, role: 'marketing', name: 'Leads Generated', target: 50, weightage: 25 },
                    { id: 12, role: 'marketing', name: 'Campaign ROI', target: 200, weightage: 30 },
                    { id: 13, role: 'marketing', name: 'Website Traffic', target: 10000, weightage: 20 },
                    { id: 14, role: 'marketing', name: 'Cost per Lead', target: 50, weightage: 15 },
                    { id: 15, role: 'marketing', name: 'Conversion Rate', target: 5, weightage: 10 },
                    { id: 16, role: 'developer', name: 'Sprint Velocity', target: 40, weightage: 20 },
                    { id: 17, role: 'developer', name: 'Code Quality', target: 85, weightage: 25 },
                    { id: 18, role: 'developer', name: 'Bug Resolution', target: 90, weightage: 20 },
                    { id: 19, role: 'developer', name: 'Documentation', target: 80, weightage: 15 },
                    { id: 20, role: 'developer', name: 'Team Collaboration', target: 85, weightage: 20 },
                    { id: 21, role: 'admin', name: 'Task Completion', target: 95, weightage: 30 },
                    { id: 22, role: 'admin', name: 'Vendor SLA', target: 90, weightage: 20 },
                    { id: 23, role: 'admin', name: 'Expense Control', target: 100, weightage: 20 },
                    { id: 24, role: 'admin', name: 'Asset Accuracy', target: 98, weightage: 15 },
                    { id: 25, role: 'admin', name: 'Compliance Score', target: 95, weightage: 15 },
                    { id: 26, role: 'hr', name: 'Time to Hire', target: 30, weightage: 20 },
                    { id: 27, role: 'hr', name: 'Offer Acceptance', target: 80, weightage: 20 },
                    { id: 28, role: 'hr', name: 'Employee Retention', target: 90, weightage: 25 },
                    { id: 29, role: 'hr', name: 'Training Completion', target: 85, weightage: 20 },
                    { id: 30, role: 'hr', name: 'Compliance', target: 98, weightage: 15 },
                ],
                performances: [
                    { id: 1, employeeId: 1, reviewer: 'Admin', date: '2026-07-15', rating: 4.5,
                        comments: 'Excellent technical skills and teamwork.', kpiScore: 88, overallScore: 4.5 },
                    { id: 2, employeeId: 2, reviewer: 'Admin', date: '2026-07-10', rating: 4.0,
                        comments: 'Strong sales performance, leadership.', kpiScore: 82, overallScore: 4.0 },
                    { id: 3, employeeId: 3, reviewer: 'HR Manager', date: '2026-06-28', rating: 3.5,
                        comments: 'Good creativity, needs more data-driven approach.', kpiScore: 75,
                        overallScore: 3.5 },
                    { id: 4, employeeId: 6, reviewer: 'Michael Torres', date: '2026-07-20', rating: 4.2,
                        comments: 'Excellent telecalling skills, high conversion.', kpiScore: 86,
                        overallScore: 4.2 },
                    { id: 5, employeeId: 7, reviewer: 'Sarah Kim', date: '2026-07-18', rating: 4.0,
                        comments: 'Great content creation, engagement improving.', kpiScore: 80,
                        overallScore: 4.0 },
                ],
                incentives: [
                    { id: 1, employeeId: 6, department: 'Sales', plan: 'Telecaller Incentive', kpi: 'Conversion',
                        target: 20, achievement: 26, achievementPct: 130, slab: 'A', rate: 500, amount: 6500,
                        status: 'approved', paymentStatus: 'paid', paymentDate: '2026-08-05' },
                    { id: 2, employeeId: 7, department: 'Marketing', plan: 'Social Media Bonus', kpi: 'Engagement',
                        target: 5, achievement: 6.5, achievementPct: 130, slab: 'A', rate: 300, amount: 3900,
                        status: 'pending', paymentStatus: 'unpaid', paymentDate: '' },
                ],
                grievances: [
                    { id: 1, employeeId: 3, category: 'Workplace', description: 'Need better lighting in cabin area.',
                        date: '2026-07-25', priority: 'Medium', assignedHR: 'Priya Sharma',
                        status: 'in-progress' },
                ],
                exitManagement: [
                    { id: 1, employeeId: 7, resignationDate: '2026-07-28', reason: 'Better opportunity',
                        lastWorkingDate: '2026-08-28', noticePeriod: 30, status: 'pending', managerApproval: false,
                        hrApproval: false, clearance: false, finalSettlement: false },
                ],
                assets: [
                    { id: 1, employeeId: 1, assetType: 'Laptop', assetName: 'MacBook Pro M2', serialNumber: 'MP12345',
                        assetTag: 'AST-001', purchaseDate: '2023-06-01', cost: 2400, warranty: '2025-06-01',
                        assignedDate: '2023-06-01', condition: 'Good', location: 'NYC Office',
                        status: 'assigned' },
                    { id: 2, employeeId: 2, assetType: 'Phone', assetName: 'iPhone 14', serialNumber: 'IP67890',
                        assetTag: 'AST-002', purchaseDate: '2023-11-15', cost: 999, warranty: '2024-11-15',
                        assignedDate: '2023-11-15', condition: 'Excellent', location: 'LA Office',
                        status: 'assigned' },
                ],
                expenses: [
                    { id: 1, employeeId: 3, category: 'Travel', expenseDate: '2026-07-20', amount: 450, gst: 45,
                        purpose: 'Client meeting', project: 'Q3 Marketing', costCenter: 'MKT-001',
                        paymentMode: 'Company Card', status: 'approved', submittedDate: '2026-07-21',
                        approvedBy: 'Admin' },
                ],
                announcements: [
                    { id: 1, title: 'Q3 All-Hands Meeting', category: 'Company',
                        message: 'Please join the Q3 all-hands meeting on Aug 15.',
                        priority: 'High', publishDate: '2026-08-01', expiryDate: '2026-08-16', readCount: 42,
                        acknowledgementRequired: true, acknowledgedEmployees: [] },
                ],
                trainings: [
                    { id: 1, employeeId: 1, skill: 'Kubernetes', trainingName: 'K8s Advanced',
                        provider: 'Pluralsight',
                        startDate: '2026-07-01', endDate: '2026-07-30', hours: 20, cost: 500, status: 'completed',
                        score: 92, certificate: 'K8S-2026-001' },
                    { id: 2, employeeId: 6, skill: 'Sales Techniques', trainingName: 'Advanced Telecalling',
                        provider: 'Sales Academy', startDate: '2026-08-01', endDate: '2026-08-15', hours: 15,
                        cost: 300,
                        status: 'in-progress', score: 0, certificate: '' },
                ],
                promotions: [
                    { id: 1, employeeId: 5, currentRole: 'HR Coordinator', currentGrade: 'L3',
                        proposedRole: 'HR Business Partner', proposedGrade: 'L4', performanceScore: 4.2,
                        skills: 'Recruitment,Employee Relations', experience: '3 years', certifications: 'SHRM-CP',
                        leadershipScore: 4.0, readiness: 'Ready', managerRecommendation: 'Highly Recommended',
                        hrRecommendation: 'Approved', status: 'approved', effectiveDate: '2026-09-01' },
                ],
                pips: [
                    { id: 1, employeeId: 3, manager: 'Admin', startDate: '2026-07-15', endDate: '2026-09-15',
                        performanceIssue: 'Missed campaign targets 2 consecutive months',
                        rootCause: 'Lack of data-driven approach',
                        improvementTarget: 'Increase conversion by 15%',
                        supportProvided: 'Mentoring, Data analytics training', weeklyReview: 'Weekly',
                        progressPct: 40,
                        status: 'in-progress' },
                ],
                helpdeskTickets: [
                    { id: 1, employeeId: 2, category: 'Payroll', subject: 'Salary discrepancy',
                        description: 'My August salary seems lower than expected.', priority: 'High',
                        assignedHR: 'Priya Sharma', status: 'in-progress', sla: '24 hours', resolution: '',
                        employeeRating: 0 },
                ],
                timeEvents: [
                    { id: 1, employeeId: 1, eventType: 'CHECK_IN', timestamp: '2026-08-11 09:05:12', serverTimestamp: '2026-08-11 09:05:14', location: 'NYC Office', lat: 40.7128, lng: -74.0060, source: 'Web', device: 'Chrome/Desktop', previousState: 'NOT_STARTED', newState: 'WORKING', verification: 'Geofence', status: 'verified' },
                    { id: 2, employeeId: 1, eventType: 'BREAK_START', timestamp: '2026-08-11 11:02:18', serverTimestamp: '2026-08-11 11:02:19', location: 'NYC Office', source: 'Web', device: 'Chrome/Desktop', previousState: 'WORKING', newState: 'BREAK', verification: 'Manual', status: 'verified' },
                    { id: 3, employeeId: 1, eventType: 'BREAK_END', timestamp: '2026-08-11 11:17:44', serverTimestamp: '2026-08-11 11:17:45', location: 'NYC Office', source: 'Web', device: 'Chrome/Desktop', previousState: 'BREAK', newState: 'WORKING', verification: 'Manual', status: 'verified' },
                    { id: 4, employeeId: 1, eventType: 'CHECK_OUT', timestamp: '2026-08-11 18:10:06', serverTimestamp: '2026-08-11 18:10:08', location: 'NYC Office', source: 'Web', device: 'Chrome/Desktop', previousState: 'WORKING', newState: 'CHECKED_OUT', verification: 'Geofence', status: 'verified' },
                ],
                breaks: [
                    { id: 1, employeeId: 1, date: '2026-08-11', breakType: 'Tea Break', startTime: '11:02', endTime: '11:17', duration: 15, allowedDuration: 15, excessDuration: 0, status: 'ok', approvedBy: '' },
                    { id: 2, employeeId: 2, date: '2026-08-11', breakType: 'Lunch', startTime: '13:00', endTime: '13:52', duration: 52, allowedDuration: 45, excessDuration: 7, status: 'overrun', approvedBy: '' },
                ],
                fieldSessions: [
                    { id: 1, employeeId: 2, date: '2026-08-10', startTime: '10:04', endTime: '16:22', duration: 378, startLocation: 'LA Office', endLocation: 'Client Site A', distanceKm: 27.4, visitCount: 4, purpose: 'Client meetings', status: 'verified', photos: 4 },
                ],
                travelSessions: [
                    { id: 1, employeeId: 2, date: '2026-08-10', startTime: '09:30', endTime: '10:04', origin: 'LA Office', destination: 'Client Site A', distanceKm: 12.1, mode: 'Car', purpose: 'Client visit', linkedVisit: 1 },
                ],
                overtimeRequests: [
                    { id: 1, employeeId: 1, date: '2026-08-08', regularHours: 9, extraHours: 1.5, otStart: '18:00', otEnd: '19:30', reason: 'Release deadline', status: 'approved', approvedBy: 'Admin User', payableHours: 1.5 },
                    { id: 2, employeeId: 6, date: '2026-08-09', regularHours: 9, extraHours: 2.0, otStart: '18:00', otEnd: '20:00', reason: 'Campaign push', status: 'pending', approvedBy: '', payableHours: 0 },
                ],
                geofences: [
                    { id: 1, name: 'NYC HQ', lat: 40.7128, lng: -74.0060, radius: 150, locationType: 'Head Office', status: 'active' },
                    { id: 2, name: 'LA Office', lat: 34.0522, lng: -118.2437, radius: 120, locationType: 'HQ', status: 'active' },
                    { id: 3, name: 'SF Gallery', lat: 37.7749, lng: -122.4194, radius: 100, locationType: 'Gallery', status: 'active' },
                ],
                timeCorrections: [
                    { id: 1, employeeId: 3, date: '2026-08-07', originalIn: '00:00', requestedIn: '09:10', originalOut: '00:00', requestedOut: '18:05', reason: 'Forgot to punch in', status: 'pending', requestedBy: 'Sarah Kim' },
                ],
                timePolicies: {
                    gracePeriod: 15,
                    minHours: 4,
                    halfDayThreshold: 4,
                    lateThreshold: 15,
                    earlyExitThreshold: 30,
                    lunchAllowance: 45,
                    teaBreakAllowance: 15,
                    maxBreaks: 3,
                    otMinHours: 0.5,
                    otApprovalRequired: true,
                    maxOtDaily: 4,
                    gpsRequired: true,
                    geofenceRequired: false,
                    photoRequiredField: true,
                    standardDailyHours: 9,
                    weeklyHours: 45
                },
                nextId: {
                    employee: 8,
                    user: 8,
                    shift: 3,
                    leaveType: 7,
                    leave: 3,
                    attendance: 8,
                    requisition: 3,
                    candidate: 3,
                    interview: 2,
                    onboarding: 2,
                    kpiTemplate: 31,
                    performance: 6,
                    incentive: 3,
                    grievance: 2,
                    exitManagement: 2,
                    asset: 3,
                    expense: 2,
                    announcement: 2,
                    training: 3,
                    promotion: 2,
                    pip: 2,
                    helpdeskTicket: 2,
                    timeEvent: 5,
                    break: 3,
                    fieldSession: 2,
                    travelSession: 2,
                    overtimeRequest: 3,
                    geofence: 4,
                    timeCorrection: 2
                },
                exceptions: [
                    { id: 1, type: 'Attendance', description: 'Emily Chen marked late 4 times this week — possible pattern.', module: 'Attendance', status: 'open', createdDate: '2026-08-18' },
                    { id: 2, type: 'Payroll', description: 'Salary variance of ₹1,200 detected for Michael Torres (net pay mismatch).', module: 'Payroll', status: 'open', createdDate: '2026-08-19' },
                    { id: 3, type: 'Compliance', description: 'Pending PAN verification for Raj Patel before payroll processing.', module: 'Compliance', status: 'open', createdDate: '2026-08-20' },
                    { id: 4, type: 'Asset', description: 'iPhone 14 (AST-002) warranty expired — schedule replacement.', module: 'Asset', status: 'resolved', createdDate: '2026-08-15' },
                ],
                auditLogs: [
                    { id: 1, timestamp: '2026-08-20 09:12:33', user: 'Admin User', action: 'LOGIN', entity: 'Session', module: 'Authentication', reference: 'admin@crm.com' },
                    { id: 2, timestamp: '2026-08-20 10:05:11', user: 'HR Manager', action: 'EMPLOYEE_CREATED', entity: 'Employee', module: 'Employee', reference: 'EMP005' },
                    { id: 3, timestamp: '2026-08-21 14:22:08', user: 'System', action: 'OFFER_GENERATED', entity: 'Offer', module: 'Offer', reference: 'OFF-2026-000001' },
                    { id: 4, timestamp: '2026-08-22 08:45:00', user: 'Admin User', action: 'ASSET_ASSIGNED', entity: 'Asset', module: 'Asset', reference: 'AST-001' },
                    { id: 5, timestamp: '2026-08-22 11:30:42', user: 'HR Manager', action: 'LEAVE_APPROVED', entity: 'Leave', module: 'Leave', reference: 'EMP002' },
                ]
            };
        }

        